defaultBaseImage: ghcr.io/distroless/static:latest

builds:
  - id: greeting
    dir: .
    main: ./main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"
